"""Prompt calibration script for the Argentine invoice extraction pipeline.

This script bypasses pytest. Invoked manually as part of D-11 phase done-gate.
Importing it during pytest collection has no side effects — all I/O lives inside
functions and the `if __name__ == '__main__'` guard. Imports SYSTEM_PROMPT from
app.services.extraction (defined as a module-level constant in Plan 02-02 Task 1)
— hence this plan declares depends_on: [02-01, 02-02].

Workflow (D-11..D-14):

  D-11: Calibration done-gate — exit 0 only when zero diffs across all fixtures.
  D-12: Ground truth generated by Claude Opus 4.7 — NEVER gpt-4o (circular bias).
  D-13: Calibration loop: generate ground truth, run GPT-4o extraction, diff field
        by field; iterate on SYSTEM_PROMPT until clean.
  D-14: anthropic package is a dev/scripts dependency only (requirements-dev.txt),
        never in main requirements.txt.

Exit codes:
  0 — Diff loop complete, all checked fixtures are clean.
  1 — Diffs found; SYSTEM_PROMPT needs tuning.
  2 — Missing required env var (OPENAI_API_KEY or ANTHROPIC_API_KEY) or no fixtures
      were checked.
"""
from __future__ import annotations

import argparse
import asyncio
import base64
import json
import os
import re
import sys
import tempfile
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Path setup: ensure 'backend/' is on sys.path so `from app.*` imports work
# when this script is invoked as `cd backend && python scripts/calibrate_prompt.py`
# (without needing an explicit PYTHONPATH= prefix).
# ---------------------------------------------------------------------------
_BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

from anthropic import Anthropic
from openai import AsyncOpenAI

from app.config import get_settings
from app.models.extraction import ExtractedInvoice
from app.services.extraction import ExtractionService, SYSTEM_PROMPT
from app.services.storage import LocalStorageBackend

# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "tests" / "fixtures"
FIXTURE_PREFIXES = ("factura_a", "factura_b", "factura_c", "remito", "lista_informal")
REPORT_PATH = FIXTURE_DIR / "calibration_report.json"
CLAUDE_MODEL = "claude-opus-4-7"  # D-12 — NEVER gpt-4o for ground truth
GPT_MODEL = "gpt-4o"
SUPPORTED_EXTS = (".jpg", ".jpeg", ".png")


# ---------------------------------------------------------------------------
# Env-var helpers
# ---------------------------------------------------------------------------


def require_env(name: str) -> str:
    """Return os.environ[name], or print an error to stderr and exit(2).

    MUST NOT print the value — only the variable name (T-02-08).
    """
    value = os.environ.get(name)
    if not value:
        print(f"missing env: {name}", file=sys.stderr)
        sys.exit(2)
    return value


# ---------------------------------------------------------------------------
# Media type detection
# ---------------------------------------------------------------------------


def detect_media_type(path: Path) -> str:
    """Return an IANA media type string for the given image path.

    Maps .jpg/.jpeg → 'image/jpeg', .png → 'image/png'.
    Falls back to 'image/jpeg' for any unrecognised extension.
    """
    ext = path.suffix.lower()
    if ext in (".jpg", ".jpeg"):
        return "image/jpeg"
    if ext == ".png":
        return "image/png"
    return "image/jpeg"


# ---------------------------------------------------------------------------
# Fixture discovery
# ---------------------------------------------------------------------------


def find_fixture(name: str) -> Path | None:
    """Search FIXTURE_DIR for {name}.jpg, .jpeg, or .png (exact name or glob prefix).

    Checks exact match first, then falls back to the first glob match for
    {name}_*.{ext} — supports descriptive filenames like factura_a_ensincro-07ene26.jpg.
    Returns the first match found, or None if the fixture is absent.
    """
    for ext in SUPPORTED_EXTS:
        candidate = FIXTURE_DIR / f"{name}{ext}"
        if candidate.exists():
            return candidate
    for ext in SUPPORTED_EXTS:
        matches = sorted(FIXTURE_DIR.glob(f"{name}_*{ext}"))
        if matches:
            return matches[0]
    return None


def find_all_fixtures(prefix: str | None = None) -> list[Path]:
    """Return all fixture image paths, optionally filtered by tipo prefix.

    Discovers every file in FIXTURE_DIR whose stem starts with a known
    FIXTURE_PREFIX and whose extension is in SUPPORTED_EXTS. Excludes
    ground-truth JSON files and non-image files automatically.

    Args:
        prefix: if given, only return fixtures whose stem starts with this
                prefix (e.g. "factura_a"). If None, return all fixtures.
    """
    results: list[Path] = []
    prefixes = (prefix,) if prefix else FIXTURE_PREFIXES
    for p in sorted(FIXTURE_DIR.iterdir()):
        if p.suffix.lower() not in SUPPORTED_EXTS:
            continue
        if any(p.stem.startswith(pfx) for pfx in prefixes):
            results.append(p)
    return results


# ---------------------------------------------------------------------------
# Ground-truth generation via Claude Opus 4.7 (D-12)
# ---------------------------------------------------------------------------


def generate_ground_truth(fixture_path: Path, schema_json_str: str) -> dict:
    """Call Claude Opus 4.7 to extract invoice fields as JSON ground truth.

    This is the ONLY place that uses CLAUDE_MODEL — never gpt-4o for ground
    truth (D-12: circular bias). The ExtractedInvoice JSON Schema is embedded
    in the prompt so Claude outputs a schema-conforming structure.

    Returns the parsed JSON dict. The caller writes it to disk.
    """
    image_bytes = fixture_path.read_bytes()
    image_data = base64.b64encode(image_bytes).decode("utf-8")
    media_type = detect_media_type(fixture_path)

    client = Anthropic()  # reads ANTHROPIC_API_KEY from env; never prints it
    response = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=4096,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": (
                            "Extract all invoice fields from this Argentine purchase document "
                            "photograph and return them as a JSON object that conforms to the "
                            "following JSON Schema. Use null for any field that is not clearly "
                            "visible on the document. Never guess or hallucinate values.\n\n"
                            f"Schema:\n{schema_json_str}\n\n"
                            "Return ONLY valid JSON — no markdown fences, no commentary."
                        ),
                    },
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_type,
                            "data": image_data,
                        },
                    },
                ],
            }
        ],
    )

    raw_text = response.content[0].text.strip()
    # Strip ```json ... ``` fences if Claude includes them despite instructions
    raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text, flags=re.MULTILINE)
    raw_text = re.sub(r"\s*```$", "", raw_text, flags=re.MULTILINE)
    raw_text = raw_text.strip()

    return json.loads(raw_text)


# ---------------------------------------------------------------------------
# GPT-4o extraction via ExtractionService
# ---------------------------------------------------------------------------


async def run_gpt4o_extraction(fixture_path: Path, settings) -> dict:
    """Run ExtractionService against a fixture image using the current SYSTEM_PROMPT.

    Uses a temporary directory for LocalStorageBackend root so calibration does
    NOT pollute /data/invoices with fixture images.

    Returns the extracted invoice as a plain dict (via model_dump(mode='json')).
    """
    image_bytes = fixture_path.read_bytes()
    with tempfile.TemporaryDirectory() as tmpdir:
        storage = LocalStorageBackend(root=tmpdir)
        client = AsyncOpenAI(api_key=settings.openai_api_key)
        service = ExtractionService(
            openai_client=client,
            storage=storage,
            settings=settings,
        )
        result = await service.extract(image_bytes, fixture_path.name)
    return result.invoice.model_dump(mode="json")


# ---------------------------------------------------------------------------
# Value normalisation (reduces diff noise from numeric formatting differences)
# ---------------------------------------------------------------------------

_DECIMAL_PATTERN = re.compile(r"^-?\d+(\.\d+)?([eE][+-]?\d+)?$")


def normalize_value(v: Any) -> Any:
    """Recursively normalise extracted values before equality comparison.

    - Decimal-shaped strings ("1.00" vs "1.0") → canonical Decimal string
    - Strings: strip surrounding whitespace; empty string → None
    - Dicts: normalise each value recursively
    - Lists: normalise each element recursively
    - None and other types: pass through unchanged
    """
    if v is None:
        return None
    if isinstance(v, str):
        stripped = v.strip().rstrip(".")
        if stripped == "":
            return None
        if _DECIMAL_PATTERN.match(stripped):
            try:
                return str(Decimal(stripped).normalize())
            except InvalidOperation:
                pass
        return stripped
    if isinstance(v, (int, float, Decimal)):
        # Normalise numeric types to canonical Decimal string
        try:
            return str(Decimal(str(v)).normalize())
        except InvalidOperation:
            return str(v)
    if isinstance(v, dict):
        return {k: normalize_value(val) for k, val in v.items()}
    if isinstance(v, list):
        return [normalize_value(item) for item in v]
    return v


# ---------------------------------------------------------------------------
# Field-by-field diff
# ---------------------------------------------------------------------------


def diff_invoice(ground_truth: dict, extracted: dict, path: str = "") -> list[str]:
    """Recursively compare ground_truth and extracted dicts field by field.

    Returns a list of human-readable diff strings such as:
      "tipo_comprobante: ground_truth=FACTURA_A, extracted=FACTURA_B"

    Line items are sorted by `descripcion` before comparing to reduce false
    positives from GPT-4o row reordering (review LOW #7):
    # Sort by descripcion before comparing — GPT-4o frequently reorders line
    # item rows; without this sort, item-by-item diffs produce spurious false
    # positives.
    """
    diffs: list[str] = []

    all_keys = set(ground_truth) | set(extracted)

    for key in sorted(all_keys):
        field_path = f"{path}.{key}" if path else key
        gt_val = ground_truth.get(key)
        ex_val = extracted.get(key)

        # Special handling for line_items (or any list of dicts keyed by descripcion)
        if isinstance(gt_val, list) and isinstance(ex_val, list):
            # Sort by descripcion before comparing — GPT-4o frequently reorders line
            # item rows; without this sort, item-by-item diffs produce spurious false
            # positives.
            gt_sorted = sorted(
                gt_val,
                key=lambda x: (x.get("descripcion") or "") if isinstance(x, dict) else "",
            )
            ex_sorted = sorted(
                ex_val,
                key=lambda x: (x.get("descripcion") or "") if isinstance(x, dict) else "",
            )

            if len(gt_sorted) != len(ex_sorted):
                diffs.append(
                    f"{field_path}: len(gt)={len(gt_sorted)} len(ext)={len(ex_sorted)}"
                )
            else:
                for i, (gt_item, ex_item) in enumerate(zip(gt_sorted, ex_sorted)):
                    item_path = f"{field_path}[{i}]"
                    if isinstance(gt_item, dict) and isinstance(ex_item, dict):
                        diffs.extend(diff_invoice(gt_item, ex_item, path=item_path))
                    else:
                        n_gt = normalize_value(gt_item)
                        n_ex = normalize_value(ex_item)
                        if n_gt != n_ex:
                            diffs.append(
                                f"{item_path}: ground_truth={n_gt!r}, extracted={n_ex!r}"
                            )
            continue

        # Nested dicts
        if isinstance(gt_val, dict) and isinstance(ex_val, dict):
            diffs.extend(diff_invoice(gt_val, ex_val, path=field_path))
            continue

        # Scalar comparison with normalisation
        n_gt = normalize_value(gt_val)
        n_ex = normalize_value(ex_val)
        if n_gt != n_ex:
            diffs.append(
                f"{field_path}: ground_truth={n_gt!r}, extracted={n_ex!r}"
            )

    return diffs


# ---------------------------------------------------------------------------
# Command: generate ground truth
# ---------------------------------------------------------------------------


def cmd_generate_ground_truth(args) -> int:
    """Generate {stem}_ground_truth.json for each available fixture image.

    Uses Claude Opus 4.7 (CLAUDE_MODEL) — never gpt-4o (D-12).
    Discovers all fixture images whose stem starts with a known FIXTURE_PREFIX.
    Skips any image that already has a ground-truth file (pass --overwrite to force).

    Returns exit code 0 on success (skips are not failures).
    """
    require_env("ANTHROPIC_API_KEY")

    schema_json = json.dumps(
        ExtractedInvoice.model_json_schema(), indent=2, ensure_ascii=False
    )

    fixtures = find_all_fixtures(prefix=args.fixture) if args.fixture else find_all_fixtures()
    if not fixtures:
        print(f"[SKIP] no fixture images found in {FIXTURE_DIR}", file=sys.stderr)
        return 2

    for path in fixtures:
        out = FIXTURE_DIR / f"{path.stem}_ground_truth.json"
        if out.exists() and not getattr(args, "overwrite", False):
            print(f"[SKIP] {path.name}: ground truth already exists ({out.name})")
            continue

        print(f"[...] generating ground truth for {path.name} ...")
        data = generate_ground_truth(path, schema_json)
        out.write_text(json.dumps(data, indent=2, ensure_ascii=False))
        print(f"[OK] wrote {out}")

    return 0


# ---------------------------------------------------------------------------
# Command: diff loop (D-11 done-gate)
# ---------------------------------------------------------------------------


def cmd_diff(args) -> int:
    """Compare GPT-4o extractions against Opus-generated ground truth.

    For each fixture image that has a corresponding {stem}_ground_truth.json:
    - Runs GPT-4o extraction via ExtractionService using the current SYSTEM_PROMPT.
    - Diffs extracted dict against ground truth field by field.

    Writes calibration_report.json to FIXTURE_DIR.

    Exit codes:
      0 — all checked fixtures have clean diffs.
      1 — one or more diffs found.
      2 — no fixtures were checked (no images + no ground truth).
    """
    require_env("OPENAI_API_KEY")

    settings = get_settings()

    report: dict[str, Any] = {
        "system_prompt": SYSTEM_PROMPT,
        "fixtures": {},
        "clean": True,
        "checked": 0,
    }

    fixtures = find_all_fixtures(prefix=args.fixture) if args.fixture else find_all_fixtures()

    for path in fixtures:
        gt_path = FIXTURE_DIR / f"{path.stem}_ground_truth.json"
        if not gt_path.exists():
            report["fixtures"][path.stem] = {
                "status": "skip_no_ground_truth",
                "hint": "run --generate-ground-truth first",
            }
            continue

        print(f"[...] running GPT-4o extraction for {path.name} ...")
        try:
            extracted = asyncio.run(run_gpt4o_extraction(path, settings))
        except Exception as exc:
            report["clean"] = False
            report["fixtures"][path.stem] = {
                "status": "extraction_error",
                "error": str(exc),
            }
            print(f"[ERROR] {path.stem}: extraction failed — {exc}")
            continue
        ground_truth = json.loads(gt_path.read_text())

        diffs = diff_invoice(ground_truth, extracted)
        report["checked"] += 1
        report["fixtures"][path.stem] = {
            "status": "checked",
            "diff_count": len(diffs),
            "diffs": diffs,
        }

        if diffs:
            report["clean"] = False
            print(f"[DIFF {len(diffs)}] {path.stem}: {len(diffs)} diff(s) found")
            for diff_line in diffs:
                print(f"  - {diff_line}")
        else:
            print(f"[OK] {path.stem}: clean")

    REPORT_PATH.write_text(json.dumps(report, indent=2, ensure_ascii=False))
    print(f"\ncalibration_report.json: {REPORT_PATH}")

    if report["checked"] == 0:
        print("no fixtures checked", file=sys.stderr)
        return 2

    return 0 if report["clean"] else 1


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """Parse CLI flags and dispatch to the appropriate command."""
    parser = argparse.ArgumentParser(
        description=(
            "Calibration script for the Argentine invoice extraction pipeline (D-11). "
            "Generates ground truth via Claude Opus 4.7 and diffs against GPT-4o extraction."
        )
    )
    parser.add_argument(
        "--generate-ground-truth",
        action="store_true",
        help=(
            "Generate {fixture}_ground_truth.json files using Claude Opus 4.7. "
            "Requires ANTHROPIC_API_KEY."
        ),
    )
    parser.add_argument(
        "--fixture",
        type=str,
        default=None,
        help=(
            "Filter to fixtures whose stem starts with this prefix "
            "(e.g. 'factura_a', 'remito'). Operates on all fixtures if omitted."
        ),
    )
    parser.add_argument(
        "--report-only",
        action="store_true",
        help=(
            "Run the diff loop using existing ground truth files (no Anthropic call). "
            "Equivalent to running without any flag — this flag reserves the hook for "
            "future use."
        ),
    )
    args = parser.parse_args()

    if args.generate_ground_truth:
        sys.exit(cmd_generate_ground_truth(args))
    else:
        sys.exit(cmd_diff(args))


if __name__ == "__main__":
    main()
