"""initial_schema

Revision ID: 0cd640399c29
Revises: 
Create Date: 2026-05-13 14:08:44.231654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd640399c29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=50), nullable=True),
    sa.Column('numero_documento', sa.String(length=100), nullable=True),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('cuit_proveedor', sa.String(length=13), nullable=True),
    sa.Column('cae', sa.String(length=20), nullable=True),
    sa.Column('fecha_vencimiento_cae', sa.Date(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('whatsapp_message_id', sa.String(length=100), nullable=True),
    sa.Column('sender_phone', sa.String(length=30), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('raw_extraction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('ix_invoices_numero_documento_proveedor', 'invoices', ['numero_documento', 'proveedor'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('sender_allowlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo_sku', sa.String(length=100), nullable=True),
    sa.Column('bultos', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unidades_por_bulto', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('precio_unitario_sin_iva', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('descuento_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('iva_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('percepciones_iibb', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_line_items')
    op.drop_table('sender_allowlist')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_numero_documento_proveedor', table_name='invoices')
    op.drop_index('ix_invoices_created_at', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
